<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Include="logo48_48.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PlexReportII">
      <HintPath>..\..\src\PlexReportII\bin\Release\net8.0\PlexReportII.dll</HintPath>
    </Reference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.2" />
    <PackageReference Include="C1.Pdf" Version="10.0.20252.203" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>logo48_48.ico</ApplicationIcon>
  </PropertyGroup>

</Project>